### ISSUE TITLE
Python < 3.8 support?

### ISSUE THREAD

**Issue by ReiFan49** [donmai-me/MaiConverter#12]
I would like to know why the Python Version requirement is `3.8`.
I tested it locally (by changing the things to 3.7 or perhaps lower) and it works.

Unless a local runner test for this already done. Thanks!

**Comment by donmai-me** [comment]
I may have forgotten the reason why I set the requirement to 3.8 but I think the reason why is that it was the current version of Python I have installed at the time I started this repo. And I was too lazy to check on older Python versions. I can lower the required Python version to 3.7, or lower, if needed

**Comment by ReiFan49** [comment]
So far as I find out that this code is "partially compatible with 3.7 or lower".
on `maiconverter/__init__.py` there's an import notation that is can be checked by version difference, the `importlib.metadata` which is a 3.8 feature, but the backports exists for 3.7 or lower as `importlib_metadata`. Otherwise I could make use it fully on 3.7 itself.

**Comment by donmai-me** [comment]
I see. So to make it compatible with older versions I could change the import in `__init__.py` to something like this:
```python
try:
    from importlib.metadata import version, PackageNotFoundError
except ImportError:
    from importlib_metadata import version, PackageNotFoundError
```

change `python_requires` to ">=3" in`setup.py`

and add this to `setup.py`
```python
extras_require={
        ':python_version < "3.8"': [
            "importlib-metadata"
        ]
    }
```

Let me know if I miss something

**Comment by ReiFan49** [comment]
sounds fine to me, tested with installation from 3.6 and lower as well...
it sounds like the `setuptools-scm` (v6) only supports py3.7 and above as it uses `__future__.annotation` feature.

**Comment by donmai-me** [comment]
~~That means that only python versions 3.7 and above can build this package and doesn't affect older python versions from installing from a wheel file, right?~~

Edit: Nevermind. This package uses `import __future__ import annotations` too. Seems like I'll have to add `future-annotations` package in `extras_require`

**Comment by donmai-me** [comment]
I just looked at how to make `future-annotations` work and on second thought I'm not keen on adding support for it. I'd need to add an encoding cookie at the start of every file that uses annotations. Even then the backport only goes until python 3.6.1. Considering that Python 3.6 is already EOL, I'm not motivated to add support for it. 

So I'll only add support for Python 3.7 which is still actively supported.

**Comment by ReiFan49** [comment]
there's no need, unless you are *ok* with downgrading or limiting the `setuptools-scm` version. :+1:

**Comment by donmai-me** [comment]
version 0.14.6 should add support to python 3.7. If I messed up, kindly reopen this issue. Thanks again for your time
