### ISSUE TITLE
how to use the command line

### ISSUE THREAD

**Issue by DJArthur** [donmai-me/MaiConverter#15]

**Comment by DJArthur** [comment]
its seem to happen a syntax error when I type the command in cmd,I can't find the reason

**Comment by donmai-me** [comment]
You can read the readme for commandline guide https://github.com/donmai-me/MaiConverter#commandline

If you still have problems, please provide more information for me to help you

**Comment by DJArthur** [comment]
Oh,when I type the command like this:
maiconverter simaitoma2 xxxxx.txt
in the cmd,it's won't execute the command at all.I don't know any errors there.If my step is wrong

**Comment by donmai-me** [comment]
What do you mean by the command not executing? Can you share a screenshot?

**Comment by DJArthur** [comment]
it's said that"is not recognized as an internal or external command,operable program or batch flie"
