### ISSUE TITLE
Key not supplied

### ISSUE THREAD

**Issue by DJArthur** [donmai-me/MaiConverter#16]
I'm sorry to distube u so much,but when I execute the encrypt(sdt to sdb),it's said that "key not supplied".

**Comment by donmai-me** [comment]
Please see the pinned issue: https://github.com/donmai-me/MaiConverter/issues/1

You'd need to find the key on your own and I unfortunately can't give you Sega's key. If you do find they key, the instruction for how to use the key is still in the readme
