### ISSUE TITLE
SDT to SDB - Binascii Error

### ISSUE THREAD

**Issue by brian-vb** [donmai-me/MaiConverter#7]
Hi! I tried to use the encrypt function with the Finale AES Key that I have but the program keeps returning binascii error, non hexadecimal digit found. Can I check how do I resolve this issue? Thank you!

**Comment by donmai-me** [comment]
It should be fixed in version 0.14.1. Be sure to prepend a `0x` if your key is in hex.

Thank you for reporting. Closing this issue, feel free to reopen or comment here if problem still persists.

**Comment by brian-vb** [comment]
Hi! Thanks for updating. The error does not happen anymore. However, now I am getting a ValueError: invalid literal for int() with base 0. This happens both when I input the key in hex and input the key in ASCII. Is it that my key is wrong?
