### ISSUE TITLE
ma2tosimai - A problem about 360° slides.

### ISSUE THREAD

**Issue by Mizuki25AM** [donmai-me/MaiConverter#9]
When using ma2tosimai, 360° Slides will be converted to A^A (A is the same number), and it will be recognized as a clockwise rotation by default when playing, which may cause the problem of reverse direction.

使用 ma2tosimai 时，遇到 360° 的 Slide 将被转换为 A^A （A 是同一个数字），在游玩时会默认被识别为顺时针旋转，可能会导致方向转反的问题。

**Comment by donmai-me** [comment]
Thanks for reporting. Can you check if 0.14.2 fixes the problem?

**Comment by Mizuki25AM** [comment]
Test passed (as 000566_03, 000465_03).  Thanks a lot.

**Comment by donmai-me** [comment]
Thank you again for reporting and testing. Closing this issue as resolved.
